# Generated by Django 3.2.9 on 2022-01-08 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('datetime', models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 8, 14, 2, 33, 161191, tzinfo=utc))),
                ('qid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
