# Generated by Django 3.2.9 on 2022-01-08 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mentors', '0001_initial'),
        ('Ask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.CharField(default=0, max_length=1000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('datetime', models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 8, 14, 2, 33, 161191, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mentors.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('datetime', models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 8, 14, 2, 33, 161191, tzinfo=utc))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mentors.mentor')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.ask')),
            ],
        ),
    ]
